import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const staff = async (context: { supabase: any; userId: string }) => {
  const { data } = await context.supabase.rpc("current_user_role");
  if (data !== "admin" && data !== "trainer") throw new Error("You do not have permission for this action.");
};
const id = z.string().uuid();
const disasterTypes = z.enum(["Flood","Fire","Earthquake","Cyclone","Landslide","Tsunami","Drought","Industrial Accident","Building Collapse","Other"]);
const severities = z.enum(["Low","Medium","High","Critical"]);
const disasterStatuses = z.enum(["Reported","Active","Under Response","Contained","Resolved","Closed"]);

export const saveDisaster = createServerFn({ method:"POST" }).middleware([requireSupabaseAuth]).validator((input)=>z.object({ id:id.optional(), title:z.string().min(3), disasterType:disasterTypes, description:z.string(), occurredAt:z.string(), state:z.string().min(2), district:z.string().min(2), city:z.string().min(2), area:z.string(), address:z.string(), latitude:z.number().min(-90).max(90), longitude:z.number().min(-180).max(180), severity:severities, status:disasterStatuses, peopleAffected:z.number().int().min(0), injured:z.number().int().min(0), missing:z.number().int().min(0), evacuated:z.number().int().min(0), deaths:z.number().int().min(0), estimatedDamage:z.number().min(0), responseStatus:z.string().min(2) }).parse(input)).handler(async({data,context})=>{
  await staff(context); const record={title:data.title,disaster_type:data.disasterType,description:data.description,occurred_at:data.occurredAt,state:data.state,district:data.district,city:data.city,area:data.area,address:data.address,latitude:data.latitude,longitude:data.longitude,severity:data.severity,status:data.status,people_affected:data.peopleAffected,injured:data.injured,missing:data.missing,evacuated:data.evacuated,deaths:data.deaths,estimated_damage:data.estimatedDamage,response_status:data.responseStatus,reported_by:context.userId,updated_at:new Date().toISOString()};
  const result=data.id?await context.supabase.from("disasters").update(record).eq("id",data.id).select().single():await context.supabase.from("disasters").insert(record).select().single(); if(result.error)throw result.error;
  await context.supabase.from("activity_log").insert({actor_id:context.userId,event:`${data.id?"Updated":"Reported"} disaster: ${data.title}`,entity_type:"disaster",entity_id:result.data.id,action:data.id?"update":"create",module:"disasters",description:data.description}); return result.data;
});
export const deleteDisaster = createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id}).parse(v)).handler(async({data,context})=>{await staff(context);const r=await context.supabase.from("disasters").delete().eq("id",data.id);if(r.error)throw r.error;return{ok:true}});

export const saveResponseTeam=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),teamName:z.string().min(2),teamType:z.enum(["Search & Rescue","Medical","Fire & Rescue","Police","Volunteer","Logistics","Emergency Response"]),leaderId:id.nullable(),members:z.array(id),phone:z.string().min(5),currentLocation:z.string().min(2),latitude:z.number().nullable(),longitude:z.number().nullable(),availability:z.boolean(),assignedDisasterId:id.nullable(),status:z.enum(["Available","Assigned","Deployed","Unavailable","Completed"])}).parse(v)).handler(async({data,context})=>{await staff(context);const row={team_name:data.teamName,team_type:data.teamType,leader_id:data.leaderId,phone:data.phone,current_location:data.currentLocation,latitude:data.latitude,longitude:data.longitude,availability:data.availability,assigned_disaster_id:data.assignedDisasterId,status:data.status,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("response_teams").update(row).eq("id",data.id).select().single():await context.supabase.from("response_teams").insert(row).select().single();if(r.error)throw r.error;if(data.id)await context.supabase.from("response_team_members").delete().eq("team_id",r.data.id);if(data.members.length){const m=await context.supabase.from("response_team_members").insert(data.members.map(user_id=>({team_id:r.data.id,user_id})));if(m.error)throw m.error}return r.data});

export const saveShelter=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),shelterName:z.string().min(2),shelterType:z.string().min(2),state:z.string().min(2),district:z.string().min(2),city:z.string().min(2),address:z.string().min(2),latitude:z.number(),longitude:z.number(),capacity:z.number().int().min(0),currentOccupancy:z.number().int().min(0),contactPerson:z.string().min(2),contactNumber:z.string().min(5),facilities:z.array(z.string()),status:z.enum(["Open","Full","Closed","Emergency Only"])}).refine(x=>x.currentOccupancy<=x.capacity,{message:"Occupancy cannot exceed capacity"}).parse(v)).handler(async({data,context})=>{await staff(context);const row={shelter_name:data.shelterName,shelter_type:data.shelterType,state:data.state,district:data.district,city:data.city,address:data.address,latitude:data.latitude,longitude:data.longitude,capacity:data.capacity,current_occupancy:data.currentOccupancy,contact_person:data.contactPerson,contact_number:data.contactNumber,facilities:data.facilities,status:data.status,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("shelters").update(row).eq("id",data.id).select().single():await context.supabase.from("shelters").insert(row).select().single();if(r.error)throw r.error;return r.data});

export const saveEvacuation=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),disasterId:id,evacuationZone:z.string().min(2),peopleToEvacuate:z.number().int().min(0),peopleEvacuated:z.number().int().min(0),startTime:z.string().nullable(),endTime:z.string().nullable(),destinationShelterId:id.nullable(),responsibleTeamId:id.nullable(),status:z.enum(["Planned","In Progress","Completed","Cancelled"])}).refine(x=>x.peopleEvacuated<=x.peopleToEvacuate,{message:"Evacuated count cannot exceed the target"}).parse(v)).handler(async({data,context})=>{await staff(context);const row={disaster_id:data.disasterId,evacuation_zone:data.evacuationZone,people_to_evacuate:data.peopleToEvacuate,people_evacuated:data.peopleEvacuated,start_time:data.startTime,end_time:data.endTime,destination_shelter_id:data.destinationShelterId,responsible_team_id:data.responsibleTeamId,status:data.status,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("evacuations").update(row).eq("id",data.id).select().single():await context.supabase.from("evacuations").insert(row).select().single();if(r.error)throw r.error;await context.supabase.from("activity_log").insert({actor_id:context.userId,event:`Evacuation ${data.status.toLowerCase()}`,entity_type:"evacuation",entity_id:r.data.id,action:data.id?"update":"create",module:"evacuations"});return r.data});

export const saveWarehouse=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),warehouseName:z.string().min(2),location:z.string().min(2),address:z.string().min(2),manager:z.string().min(2),contact:z.string().min(5),capacity:z.number().int().min(0),currentUtilization:z.number().int().min(0),status:z.enum(["active","inactive"])}).refine(x=>x.currentUtilization<=x.capacity,{message:"Utilization cannot exceed capacity"}).parse(v)).handler(async({data,context})=>{await staff(context);const row={warehouse_name:data.warehouseName,location:data.location,address:data.address,manager:data.manager,contact:data.contact,capacity:data.capacity,current_utilization:data.currentUtilization,status:data.status,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("warehouses").update(row).eq("id",data.id).select().single():await context.supabase.from("warehouses").insert(row).select().single();if(r.error)throw r.error;return r.data});

export const saveMedicalFacility=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),hospitalName:z.string().min(2),location:z.string().min(2),address:z.string().min(2),contact:z.string().min(5),latitude:z.number().nullable(),longitude:z.number().nullable(),totalBeds:z.number().int().min(0),availableBeds:z.number().int().min(0),icuBeds:z.number().int().min(0),availableIcuBeds:z.number().int().min(0),emergencyCapacity:z.number().int().min(0),ambulanceCount:z.number().int().min(0),status:z.string().min(2)}).parse(v)).handler(async({data,context})=>{await staff(context);const row={hospital_name:data.hospitalName,location:data.location,address:data.address,contact:data.contact,latitude:data.latitude,longitude:data.longitude,total_beds:data.totalBeds,available_beds:data.availableBeds,icu_beds:data.icuBeds,available_icu_beds:data.availableIcuBeds,emergency_capacity:data.emergencyCapacity,ambulance_count:data.ambulanceCount,status:data.status,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("medical_facilities").update(row).eq("id",data.id).select().single():await context.supabase.from("medical_facilities").insert(row).select().single();if(r.error)throw r.error;return r.data});

export const saveEmergencyContact=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id:id.optional(),service:z.string().min(2),organization:z.string().min(2),contactNumber:z.string().min(5),location:z.string().min(2),availability:z.string().min(2),description:z.string()}).parse(v)).handler(async({data,context})=>{await staff(context);const row={service:data.service,organization:data.organization,contact_number:data.contactNumber,location:data.location,availability:data.availability,description:data.description,updated_at:new Date().toISOString()};const r=data.id?await context.supabase.from("emergency_contacts").update(row).eq("id",data.id).select().single():await context.supabase.from("emergency_contacts").insert(row).select().single();if(r.error)throw r.error;return r.data});

export const recordAttendance=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({participantId:id,trainingId:id,date:z.string(),status:z.enum(["Present","Absent","Late"])}).parse(v)).handler(async({data,context})=>{await staff(context);const r=await context.supabase.from("attendance_records").upsert({participant_id:data.participantId,training_id:data.trainingId,attendance_date:data.date,status:data.status},{onConflict:"participant_id,attendance_date"}).select().single();if(r.error)throw r.error;return r.data});
export const acknowledgeAlert=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id}).parse(v)).handler(async({data,context})=>{const r=await context.supabase.rpc("acknowledge_alert",{_alert_id:data.id});if(r.error)throw r.error;return r.data});
export const markNotificationRead=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((v)=>z.object({id}).parse(v)).handler(async({data,context})=>{const r=await context.supabase.from("notifications").update({read:true}).eq("id",data.id).eq("user_id",context.userId);if(r.error)throw r.error;return{ok:true}});